### ISSUE TITLE
Create PR description template

### ISSUE THREAD

**Issue by lindlands** [Green-Kittens/bathroom-finder-frontend#117]

**Comment by lindlands** [comment]
"Do I need to document this?"

**Comment by meganfung38** [comment]
Link to PR Template Document: 
https://cpslo.sharepoint.com/:w:/r/sites/csc308group6/Shared%20Documents/PR%20Template.docx?d=we064e10677d34275a45bb550d57a36fc&csf=1&web=1&e=EuASve
