### ISSUE TITLE
[REQ] Add Acceptance tests

### ISSUE THREAD

**Issue by JonasSchiessl** [Green-Kittens/bathroom-finder-frontend#139]

**Comment by dylantompkins** [comment]
_copying from delivery requirements:_

- [ ] automate with end-to-end testing and API testing
- [ ] Two end-to-end testing scenarios (pertaining the same feature or not)
- [ ] Two API testing scenarios (one using a GET and another using a POST
          endpoint, pertaining the same feature or not)
- [ ] accompanied by their acceptance criteria spec following Gherkin language
- [ ] add acceptance criteria spec of implemented tests to the "Tests" section of
          the Tech Spec
- [ ] automated acceptance tests need not be in the CI/CD pipeline (run and pass
          locally is okay)

**Comment by dltompki** [comment]
issues with Detox prevented us from implementing these
