### ISSUE TITLE
Review Spike: decide what plus symbol in navbar should do

### ISSUE THREAD

**Issue by meganfung38** [Green-Kittens/bathroom-finder-frontend#17]
- have everyone comment their opinions
- investigate implementation
- present to the team

**Comment by dylantompkins** [comment]
To clarify on my proposed UX, here's a more formal flowchart:

![](https://mermaid.ink/svg/pako:eNptkMFugzAQRH9ltadWSn6AQ6WoFHFCFekN52DZS2MVvJG9NI2Af68h5FCpPliWZ9541iMatoQZth1fzVkHgY9ceUjrYG2jMO3w5FkgXsi41hkQhkDfjq7AAVptXOfk9qzwBPv9CxTjkToyAsWmzPe0YlGnxyW8_bgocYK6eecooKFeI0__mnOmCFXqsFITVEXzGkgLJa5KPR7Gja7u-KGLvMWmd_5IOXuaoGxqkiH4ZaKSe9rwep2jxB32FHrtbPqdcZEUypl6Upilo9XhS6Hyc_LpQfh48wYzCQPtcLjYVC53-jPoHrNWd5HmX-wedgY)

**Comment by k4yluh** [comment]
I believe the plus button should be to add a new bathroom; so, when you press the button, it would immediately pull up a bathroom profile form and once they enter the location if there is already a bathroom at that location, check if there are multiple bathrooms or if they are trying to add an already existing bathroom

**Comment by JonasSchiessl** [comment]
I would agree with kayla, i think the plus button should be to add a new bathroom, it would be too confusing if it was to create a review and post a bathroom since we already have post a review on the facility profile. We can put a check in place if there already is a bathroom in place of that location.

**Comment by meganfung38** [comment]
I believe the plus button should present a modal asking the user for a location-- they have the option to choose the location of an existing bathroom facility or create a new one. 
For a new location --> navigate to create bathroom facility 
For a new review --> navigate to create review (with location selected already in place in dropdown)

**Comment by lindlands** [comment]
Would also be down to change the plus symbol to something else

**Comment by k4yluh** [comment]
Plus Button Options
1.	Enter facility location -> check if it exists or not
	If it exists, post review
	If it doesn’t exist, create a new facility, and check if user wants to create a review
Who proposed this/is for this option: Dylan, Megan, and Lindsey
Pros
-	User friendly (intuitive)
-	Gives users more options
-	Clean and fluid user interactions 
o	Follows a story 
Cons
-	May be difficult to have functionality for locations that have multiple bathrooms
-	Have to search for bathroom before you can leave review
o	Review option a bit hidden

2.	To add a new bathroom -> pulls up new bathroom form
when user entering location -> check if location already has bathroom 
	If that bathroom exists, pull up already existing bathroom and see if there is another bathroom at that location that user is trying to add
	If it doesn’t exist, allow user to create bathroom
Who proposed this/is for this option: Kayla and Jonas
Pros
-	Straight-forward
Cons
-	Not as many options

3.	Add a new bathroom or post a new review 
Who proposed this/is for this option: Lindsey, Kayla
Pros
-	Options offered up front 
-	Multiple options
-	This option is a spin off of the first option: a better version
Cons
-	Couldn’t think of any

**Comment by k4yluh** [comment]
Choosing to go forward with third option: plus button is both to create a new bathroom and review.
