### ISSUE TITLE
Pull existing locations and make them icons on map

### ISSUE THREAD

**Issue by dylantompkins** [Green-Kittens/bathroom-finder-frontend#44]

**Comment by dylantompkins** [comment]
Planned for sprint 4 but wasn't able to start because waiting on #54

**Comment by dylantompkins** [comment]
- get all facilities controller function
- map each facility into an icon component
- create a follow up task for limiting number of icons

**Comment by k4yluh** [comment]
Helped Megan -- put .5 hrs

**Comment by meganfung38** [comment]
follow up in iteration #7: #120
