### ISSUE TITLE
review form uses facility data​

### ISSUE THREAD

**Issue by dylantompkins** [Green-Kittens/bathroom-finder-frontend#67]

**Comment by dylantompkins** [comment]
call controller to populate dropdown

**Comment by dylantompkins** [comment]
- only create reviews from facility profile
- pass bathroom id from facility profile when the add review button is pressed
- display the bathroom you are reviewing on the review form in some way (replace the location dropdown)

**Comment by JonasSchiessl** [comment]
Use BathroomData branch

**Comment by lindlands** [comment]
Being done by Megan (#146)
