### ISSUE TITLE
add tags to facility form

### ISSUE THREAD

**Issue by dylantompkins** [Green-Kittens/bathroom-finder-frontend#68]

**Comment by dylantompkins** [comment]
- component to allow user to pick from existing set of tags
- component outputs a list of strings
- pass list of strings into controller to create bathroom

**Comment by k4yluh** [comment]
- sending tags to controller func 
- make ui to pick tags from a set list

**Comment by k4yluh** [comment]
Follow up in sprint 7 -- #122
